/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package market;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.objects.NativeArray;

/**
 *
 * @author Shady Elattar
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("AddProduct");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ReadProduct");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ProductinStore");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Store");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Mini of sales");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Max of sales");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Sreach");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Edit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(0, 312, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @SuppressWarnings({"UseSpecificCatch", "ConvertToTryWithResources"})

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //////////// create file and put data 
        try {

            FileOutputStream f1 = new FileOutputStream("D:\\Store.txt", true);
            DataOutputStream dos = new DataOutputStream(f1);
            String ID = JOptionPane.showInputDialog(null, "Enter ID");
            String Name = JOptionPane.showInputDialog(null, "Enter Name");
            String Quantity = JOptionPane.showInputDialog(null, "Enter Quantity");
            String UnPrice = JOptionPane.showInputDialog(null, "Enter UnitPrice");
            dos.writeUTF("\n" + ID);
            dos.writeUTF("\n" + Name);
            dos.writeUTF("\n" + Quantity);
            dos.writeUTF("\n" + UnPrice);

            dos.close();
            f1.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    @SuppressWarnings({"UseSpecificCatch", "ConvertToTryWithResources"})
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ////////////read from file
        try {
            FileInputStream f1 = new FileInputStream("D:\\Store.txt");
            DataInputStream dis = new DataInputStream(f1);

            String result = "";
            while (dis.available() > 0) {

                result += "\n" + dis.readUTF();

            }
            JOptionPane.showMessageDialog(null, result);

            dis.close();
            f1.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO DATA!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    @SuppressWarnings({"UseSpecificCatch", "ConvertToTryWithResources", "Convert2Lambda"})
    ArrayList<JButton> buttons = new ArrayList<>();
    ArrayList<Productmarket> a1 = new ArrayList<>();
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ///////////// create an button belong to product and estmit 
        a1 = new ArrayList<>();
        buttons = new ArrayList<>();
    
        try {
            FileInputStream f1 = new FileInputStream("D:\\Store.txt");
            DataInputStream dis = new DataInputStream(f1);
            while (dis.available() > 0) {
                Productmarket pro = new Productmarket();
                pro.ID = dis.readUTF();
                pro.Name = dis.readUTF();
                pro.Quantity = (Double.parseDouble(dis.readUTF()));
                pro.UnPrice = Double.parseDouble(dis.readUTF());
                a1.add(pro);
            }
            dis.close();
            f1.close();
        } catch (Exception e) {

        }
        double[] x = new double[a1.size()]; // array to save quantity 

        for (int i = 0; i < a1.size(); i++) {
            JButton b = new JButton();

            b.setText(String.valueOf(a1.get(i).Name));
            b.setBackground(Color.green);
            b.setBounds(i * 100, 100, 80, 50);
            this.getContentPane().add(b);
            this.repaint();
            buttons.add(b);
            x[i] = a1.get(i).Quantity; // array to save quantity 
            b.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    JButton a = (JButton) e.getSource();
                    String Name = a.getText();
                    String ID = "";
                    double Quantity = 0;
                    double UnPrice = 0;
                    boolean inStore = false;
                    try {
                        for (int i = 0; i < a1.size(); i++) {
                            if (a1.get(i).Name.equals(Name)) {
                                //  JOptionPane.showMessageDialog(null,x[i]);
                                Quantity = Double.parseDouble(JOptionPane.showInputDialog(null, "Enter Quantity"));
                                if (a1.get(i).Quantity >= Quantity) {
                                    a1.get(i).Quantity = a1.get(i).Quantity - Quantity;

                                    if ((x[i] / 2) >= a1.get(i).Quantity) {
                                        b.setBackground(Color.YELLOW);
                                    }

                                    if ((x[i] / 4) >= a1.get(i).Quantity) {
                                        b.setBackground(Color.RED);
                                        JOptionPane.showMessageDialog(null, "Please Bring :" + a1.get(i).Name + "\n" + " Reset of Quantity =" + a1.get(i).Quantity);
                                    }

                                    ID = a1.get(i).ID;
                                    UnPrice = a1.get(i).UnPrice;

                                    FileOutputStream f1 = new FileOutputStream("E:\\inStore.txt", true);
                                    DataOutputStream dos = new DataOutputStream(f1);
                                    dos.writeUTF("\n" + ID);
                                    dos.writeUTF("\n" + Name);
                                    dos.writeUTF("\n" + a1.get(i).Quantity);
                                    dos.writeUTF("\n" + UnPrice);
                                    dos.close();
                                    f1.close();
                                    inStore = true;
                                }
                            }
                        }
                        if (inStore == false) {
                            JOptionPane.showMessageDialog(null, "3ady 3lana b3den");
                        }

                    } catch (Exception ea) {
                    }
                }
            });

        }

        if (a1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No DATA !");
        }

    }//GEN-LAST:event_jButton3ActionPerformed
    @SuppressWarnings({"UseSpecificCatch", "ConvertToTryWithResources"})
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            FileInputStream f1 = new FileInputStream("D:\\inStore.txt");
            DataInputStream d1 = new DataInputStream(f1);
            String x = "";
            while (d1.available() > 0) {
                x += "\n" + d1.readUTF();
            }
            JOptionPane.showMessageDialog(null, x);
            d1.close();
            f1.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO DATA !");
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        a1.clear();

        for (JButton obj : buttons) {
            this.getContentPane().remove(obj);
        }

        this.repaint();

        File out = new File("E:\\Store.txt");
        out.delete();

        File in = new File("E:\\inStore.txt");
        in.delete();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Max
        ArrayList<Productmarket> a1 = new ArrayList<>();
        try {
            FileInputStream f1 = new FileInputStream("D:\\Store.txt");
            DataInputStream dis = new DataInputStream(f1);
            while (dis.available() > 0) {
                Productmarket pro = new Productmarket();
                pro.ID = dis.readUTF();
                pro.Name = dis.readUTF();
                pro.Quantity = Double.parseDouble(dis.readUTF());
                pro.UnPrice = Double.parseDouble(dis.readUTF());
                a1.add(pro);
            }
            dis.close();
            f1.close();
        } catch (Exception e) {

        }
        String Name = "";
        double Max = 0;
        double cmin = 0;
        for (int i = 0; i < a1.size(); i++) {

            cmin = a1.get(i).Quantity;
            if (cmin > Max) {
                Max = cmin;
                Name = a1.get(i).Name;
            }

        }
        JOptionPane.showMessageDialog(null, "Name of product " + Name + " is :" + Max);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        //MIN
        ArrayList<Productmarket> a1 = new ArrayList<>();
        try {
            FileInputStream f1 = new FileInputStream("D:\\Store.txt");
            DataInputStream dis = new DataInputStream(f1);
            while (dis.available() > 0) {
                Productmarket pro = new Productmarket();
                pro.ID = dis.readUTF();
                pro.Name = dis.readUTF();
                pro.Quantity = Double.parseDouble(dis.readUTF());
                pro.UnPrice = Double.parseDouble(dis.readUTF());
                a1.add(pro);
            }
            dis.close();
            f1.close();
        } catch (Exception e) {

        }
        String Name = "";
        Name = a1.get(0).Name;

        double Min = 0;
        Min = a1.get(0).Quantity;
        double cmin = 0;
        for (int i = 0; i < a1.size(); i++) {

            cmin = a1.get(i).Quantity;
            if (cmin < Min) {
                Min = cmin;
                Name = a1.get(i).Name;
            }

        }
        JOptionPane.showMessageDialog(null, "Name of product " + Name + " is :" + Min);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            FileInputStream f2 = new FileInputStream("D:\\Store.txt");
            DataInputStream dis = new DataInputStream(f2);
            String Traget = JOptionPane.showInputDialog(null, "Enter Traget");
            while (dis.available() > 0) {
                String ID = dis.readUTF();
                String Name = dis.readUTF();
                String q = dis.readUTF();
                String p = dis.readUTF();

                if (Name.trim().equals(Traget)) {
                    JOptionPane.showMessageDialog(null, "Quantity :" + q + "\n" + "Unit Price :" + p);

                }

            }

            f2.close();
            dis.close();
        } catch (Exception e) {

        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            String Traget = JOptionPane.showInputDialog(null, "Enter Traget");
            FileInputStream f2 = new FileInputStream("D:\\Store.txt");
            DataInputStream dis = new DataInputStream(f2);
            FileOutputStream f3 = new FileOutputStream("D:\\Store2.txt");
            DataOutputStream dos2 = new DataOutputStream(f3);

            while (dis.available() > 0) {
                String ID = dis.readUTF();
                String Name = dis.readUTF();
                String q = dis.readUTF();
                String p = dis.readUTF();

                if (!Name.trim().equals(Traget)) {
                    dos2.writeUTF("\n" + ID);
                    dos2.writeUTF("\n" + Name);
                    dos2.writeUTF("\n" + q);
                    dos2.writeUTF("\n" + p);

                } else {
                    String newq = JOptionPane.showInputDialog(null, "Enter new Quantity");
                    String newp = JOptionPane.showInputDialog(null, "Enter new Price");
                    dos2.writeUTF("\n" + ID);
                    dos2.writeUTF("\n" + Name);
                    dos2.writeUTF("\n" + newq);
                    dos2.writeUTF("\n" + newp);
                }
            }

            f2.close();
            dis.close();
            f3.close();
            dos2.close();
            File f = new File("E:\\Store.txt");
            f.delete();
            File frename = new File("E:\\Store2.txt");
            frename.renameTo(f);
        } catch (Exception e) {

        }


    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
